# Generated by Django 3.0 on 2021-11-09 04:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=10)),
                ('studentPhone', phonenumber_field.modelfields.PhoneNumberField(default='+91', max_length=128, region=None)),
                ('studentGender', models.CharField(max_length=20)),
                ('studentDOB', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('user_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('studentDesc', models.TextField(null=True)),
                ('studentCollege', models.CharField(max_length=100)),
                ('collegeState', models.CharField(max_length=50)),
                ('yearOfStudy', models.CharField(max_length=2, null=True)),
                ('studentPic', models.ImageField(blank=True, null=True, upload_to='facultyProfile/')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyName', models.CharField(max_length=10)),
                ('facultyPhone', phonenumber_field.modelfields.PhoneNumberField(default='+91', max_length=128, region=None)),
                ('user_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('facultyDesc', models.TextField(null=True)),
                ('facultyDOB', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('facultyCollege', models.CharField(max_length=100)),
                ('collegeState', models.CharField(max_length=50)),
                ('facultyPic', models.ImageField(blank=True, null=True, upload_to='facultyProfile/')),
                ('facultyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
