# Generated by Django 3.0 on 2021-11-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultydetails',
            name='facultyPic',
            field=models.ImageField(blank=True, null=True, upload_to='facultyPic/'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='studentPic',
            field=models.ImageField(blank=True, null=True, upload_to='StudentPic/'),
        ),
    ]
