# Generated by Django 3.0 on 2021-11-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211109_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultydetails',
            name='experience',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='facultydetails',
            name='facultyGender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
