# Generated by Django 3.0 on 2021-11-10 12:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20211109_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultydetails',
            name='facultyName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='studentName',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('classId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('classname', models.CharField(max_length=50)),
                ('classDepartment', models.CharField(max_length=50)),
                ('academicYear', models.CharField(max_length=2)),
                ('classLink', models.TextField(null=True)),
                ('classFacultyName', models.CharField(max_length=100)),
                ('classTimeTable', models.TextField(null=True)),
                ('classCreationTime', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('classFacultyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.FacultyDetails')),
            ],
        ),
    ]
