# Generated by Django 3.0 on 2021-11-13 14:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211110_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcementId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('announcementHeading', models.TextField(null=True)),
                ('announcementCreationTime', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ClassRoom')),
            ],
        ),
    ]
