# Generated by Django 3.0 on 2021-11-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcementDescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcementHeading',
            field=models.CharField(max_length=50),
        ),
    ]
