# Generated by Django 3.0 on 2021-11-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20211113_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcementDescription',
            field=models.TextField(),
        ),
    ]
