# Generated by Django 3.0 on 2021-11-14 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_studentclassroomlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclassroomlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentclassroomlist',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.StudentDetails'),
        ),
    ]
