# Generated by Django 3.0 on 2021-11-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20211114_1225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentClassroomList',
        ),
    ]
