# Generated by Django 3.0 on 2021-11-14 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_studentclassroomlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassroomList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classList', models.TextField(blank=True, null=True)),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.StudentDetails')),
            ],
        ),
    ]
