# Generated by Django 3.0 on 2021-11-14 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20211114_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassroomlist',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.StudentDetails'),
        ),
    ]
