# Generated by Django 3.0 on 2021-11-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20211114_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='studentId',
        ),
        migrations.DeleteModel(
            name='StudentClassroomList',
        ),
        migrations.DeleteModel(
            name='StudentDetails',
        ),
    ]
