# Generated by Django 3.0 on 2021-11-14 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20211114_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomStudentsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.TextField(blank=True, null=True)),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ClassRoom')),
            ],
        ),
    ]
