# Generated by Django 3.0 on 2021-11-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='announcementCreationTime',
            new_name='publishedTime',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='assignmentCreationTime',
            new_name='publishedTime',
        ),
    ]
