# Generated by Django 3.0 on 2021-11-16 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20211115_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('attendenceId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('totalClassConducted', models.BigIntegerField(blank=True, default=0, null=True)),
                ('attendenceList', models.TextField(blank=True, default='{}', null=True)),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ClassRoom')),
            ],
        ),
    ]
