# Generated by Django 3.0 on 2021-11-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='studentAttendence',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
