# Generated by Django 3.0 on 2021-11-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_offlineclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineclass',
            name='offlineStatus',
            field=models.CharField(blank=True, default='NO', max_length=5, null=True),
        ),
    ]
