# Generated by Django 3.0 on 2021-11-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_vaccinestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classTimeTable',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
