# Generated by Django 3.0 on 2021-11-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20211120_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='studentDepartment',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
    ]
